package trans

const (
	RULES_AND_FAQ_of_GROPNAME = "RULES_AND_FAQ_of_GROPNAME"
	PLEASE_ACCEPT_RULES       = "PLEASE_ACCEPT_RULES"
	I_ACCEPT_RULES            = "I_ACCEPT_RULES"

	FAQ_TITLE                 = "FAQ_TITLE"
	PLEASE_READ_RULES_AND_FAQ = "PLEASE_READ_RULES_AND_FAQ"

	USERNAME_JOINED_GROUP    = "USERNAME_JOINED_GROUP"
	NUMBER_OF_JOINED_MEMBERS = "NUMBER_OF_JOINED_MEMBERS"
)
